# All endpoint constants for the GroupChannel resource
GROUP_CHANNEL_ACCEPT_INVITATION = "/accept"
GROUP_CHANNEL_CHECK_IF_MEMBER = "/members/{user_id}"
GROUP_CHANNEL_HIDE = "/hide"
GROUP_CHANNEL_JOIN = "/join"
GROUP_CHANNEL_LEAVE = "/leave"
GROUP_CHANNEL_LIST_MEMBERS = "/members"
GROUP_CHANNEL_REJECT_INVITATION = "/members/reject"
GROUP_CHANNEL_RESET_CHAT_HISTORY = "/reset_user_history"
GROUP_CHANNEL_UNHIDE = "/hide"
